### ISSUE TITLE
Test Express & usage

### ISSUE THREAD

**Issue by flockonus** [axiomzen/express-interceptor#1]
- [x] static page
- [x] render jade
- [ ] multiple writes

**Comment by p1nox** [comment]
What do you mean by "multiple writes"?

**Comment by flockonus** [comment]
Something that call more than once `res.write`, so we simulate packages that might be streaming data. Or we could try using one that actually does it

**Comment by p1nox** [comment]
Maybe you can implement an example for that, I'm not sure how to structure it and describe it.

**Comment by flockonus** [comment]
i'll put in the TO DO list but can't do just yet :disappointed:

**Comment by gustavnikolaj** [comment]
Seems related to #15 :-)

**Comment by p1nox** [comment]
Yup @gustavnikolaj , but this was more related to tests ;). I'll close this because tests will be included for sure along with the streaming feature.
