### ISSUE TITLE
Add a CONTRIBUTING Guide

### ISSUE THREAD

**Issue by pnavarrc** [axiomzen/express-interceptor#13]
Adding a contributing guide will reduce friction of possible contributors and help them to follow the project process to include new features, tests or documentation.

I ran [flint](https://github.com/pengwynn/flint) (a tool to examine projects for obstacles to contribution) which generates the following report:

```
[ERROR] CONTRIBUTING guide not found
[INFO] Add a guide for potential contributors. http://git.io/z-TiGg
[WARNING] Bootstrap script not found
[INFO] A bootstrap script makes setup a snap. http://bit.ly/JZjVL6
[WARNING] Test script not found
[INFO] Make it easy to run the test suite regardless of project type. http://bit.ly/JZjVL6
[CRITICAL] Some critical problems found.
```

Clickable links:
- [Contributing](http://git.io/z-TiGg)
- [Bootstrap script](http://bit.ly/JZjVL6)
- [Testing](http://bit.ly/JZjVL6)

**Comment by flockonus** [comment]
Very interesting, specially like the [1st](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) reference, i have some ideas of raw content to write, feel free to start ahead.
