### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by gustavnikolaj** [axiomzen/express-interceptor#15]
Hi!

I just merged a pull-request in [express-jsxtransformer](https://github.com/gustavnikolaj/express-jsxtransform) from @fer8a. This module looks very nice and solves the problem that [express-highjackresponse](https://github.com/papandreou/express-hijackresponse) solves in a much prettier way. There's only one problem, and that is the lack of support for streaming.

It's not a problem for modules like express-jsxtransformer, as that is buffering up stuff any way, but it would be nice to see it solved.

Do you have any plans about supporting streaming as well?

/cc @papandreou

**Comment by flockonus** [comment]
Hi @gustavnikolaj, glad you enjoyed, having a solid and simple use case was our main goal.

The package we've been developing that motivated interceptor also does buffering (we need the whole HTML and change it at once) but definitely streaming can make a strong use case, and thinking of the internals it seems possible, some suggestion on the API for it?

Also, in case you are using [ZenHub](https://www.zenhub.io/) we are experimenting with prioritizing issues using +1 :)

**Comment by gustavnikolaj** [comment]
As for the API I'd wish that it could be as simple as adding another method, along side intercept, called interceptStream. But I'm not sure that would be enough.

[livestyle](https://github.com/One-com/livestyle) which @Munter mentioned in #6 uses the streaming functionality of express-hijackresponse, to inject a script tag in html.

I cannot see if it would fit into how you're doing things, or if you need the kind of granular control that express-hijackresponse gives you.

**Comment by gustavnikolaj** [comment]
I will humbly plug my own module here, https://github.com/gustavnikolaj/hijackresponse, which is the spiritual successor to express-hijackresponse. It works much in the same way, and allows you to solve the more demanding problems that the abstraction in express-interceptor does not let you get into.

I think that there's room for both modules, as express-interceptor might be a lot simpler to get into for people with less demanding use cases. And I can't really see how we could provide people with the power of hijackresponse, while keeping the abstraction simple in express-interceptor.

**Comment by p1nox** [comment]
You're totally right @gustavnikolaj, I think both modules can coexists. The idea of `express-interceptor` is to provide a simple api for the most common scenarios.

I'll be adding [hijackresponse](https://github.com/gustavnikolaj/hijackresponse) to our readme file, explaining differences between both modules.

**Comment by p1nox** [comment]
@gustavnikolaj a link to your module and a recommendation if users have problems with [streaming](https://github.com/axiomzen/express-interceptor#similar-to) was added to our readme :+1:. Closing this for now.

**Comment by gustavnikolaj** [comment]
@p1nox Thanks. express-hijackresponse is sort of deprecated now that hijackresponse is out. It's the exact same API, but without monkey patching the response object. :-) https://github.com/papandreou/express-hijackresponse#deprecation-notice
