### ISSUE TITLE
Intercepting non streaming responses

### ISSUE THREAD

**Issue by gustavnikolaj** [axiomzen/express-interceptor#22]
I tried to make a test case for this using the supertest module, but I was unable to make it show properly. Using the below server implementation I was able to show the problem using curl.

```js
require('express')()
    .use(function (req, res, next) {
        console.log(new Date(), req.originalUrl);
        next();
    })
    .use(require('./index')(function (req, res) {
        return {
            isInterceptable: function () {
                var bool = /intercept$/.test(req.originalUrl);
                console.log(bool);
                return bool;
            },
            intercept: function (body, send) {
                send('intercepting yo!');
            }
        };
    }))
    .use(function (req, res, next) {
        return res.status(200).end('not intercepted!');
    })
    .listen(8888, function () {
        console.log('listening on port 8888');
    });
```

Expected result:
```
$ curl http://localhost:8888/
not intercepted!
$ curl http://localhost:8888/intercept
intercepted yo!
```

Actual result:
```
$ curl http://localhost:8888/
$ curl http://localhost:8888/intercept
intercepted yo!
```

Turns out that the non streaming responses is swallowed in the current implementation. The following change to the server fixes it:

```js
require('express')()
    .use(function (req, res, next) {
        console.log(new Date(), req.originalUrl);
        next();
    })
    .use(require('./index')(function (req, res) {
        return {
            isInterceptable: function () {
                var bool = /intercept$/.test(req.originalUrl);
                console.log(bool);
                return bool;
            },
            intercept: function (body, send) {
                send('intercepting yo!');
            }
        };
    }))
    .use(function (req, res, next) {
        res.status(200);
        res.write('not ');
        res.write('intercepted!');
        res.end();
    })
    .listen(8888, function () {
        console.log('listening on port 8888');
    });
```

**Comment by gustavnikolaj** [comment]
I had a lot of trouble working with the test suite. I'd like to send a pull request rewriting it to use https://www.npmjs.com/package/unexpected-express if you would like to see the difference between the current test suite with `supertest` and `unexpected-express`. Just let me know and I'll shoot a PR - no strings attached :-)

**Comment by flockonus** [comment]
Hi @gustavnikolaj, absolutely if you have it in hand please PR it over so @p1nox and I can check it as soon as we clear sometime!
As a little background we've been working intensively at Sesame CMS that we'll be publishing soon and Raul also has been developing Eilhard which is pretty cool and is coming even sooner.

**Comment by p1nox** [comment]
Awesome @gustavnikolaj! Indeed, we will check it out as soon as we have some time to spear, you are welcome to submit a PR :+1:.

**Comment by gustavnikolaj** [comment]
Pull request is sent, and referenced above. Besides the rewrite, it also fixes this problem.

**Comment by gustavnikolaj** [comment]
I can make a fix for this using your current test suite, now that I've been able to diagnose the problem.

Your current test suite can actually show the problem quite easily. Just replace all occurrences of `res.text` with `res.body` and you have some failing tests because of this.

The problem is that you throw away the chunk passed to res.end, here: https://github.com/axiomzen/express-interceptor/blob/master/index.js#L62

res.text is a buffered version of res.body that the http request library superagent introduces (https://github.com/visionmedia/superagent/blob/master/lib/node/parsers/text.js). supertest  uses superagent internally to do the requesting. This ends up masking the problem in your current test suite. `res.text` is fine as a convenience method in a http client library, but it is dangerous in an assertion library, at least in libraries like this one where you are having to play tricks on express and the response object.

Unexpected Express works better in this case, as it is not mangling the response object at all. It serializes the response object, and then goes on to parse it the stuff that would have been transmitted out over the network. That turns out to be more trustworthy and fitting for this use case. And I'd argue that it is a better fit.

**Comment by flockonus** [comment]
Thank you @gustavnikolaj for the insights, reading it makes sense, i'll review your PR and go deeper on the logic over the weekend.

**Comment by flockonus** [comment]
Sorry still didn't have the time, my girlfriend left this week, it was busier than i thought, by latest this weekend now.

**Comment by gustavnikolaj** [comment]
Take your time :-) This issue is not blocking me for working on anything at the moment.

If you would like to, we can find a time where we can talk about the PR. Or even review it together if you prefer that. I'm out on the country side this weekend, and I'm in Denmark, and you're in Canada. So it might take a little coordination. I'm usually on gitter.im/unexpectedjs/unexpected - and you're welcome to reach out on mail too, gustavnikolaj@gmail.com. Let me know if I can be of any assistance.

**Comment by flockonus** [comment]
Thanks for the understanding Gustav, you are a utopic collaborator. Yesterday was my last day on the job (taking a break now), and on top of that, we [hosted a hackaton](https://twitter.com/search?q=%23apifest&src=typd) the whole weekend. Now I'm winding down on commitments and will have it reviewed soon.

**Comment by gustavnikolaj** [comment]
Hi @flockonus. Do you have any update on the situation? :-)

**Comment by flockonus** [comment]
Hi @gustavnikolaj not yet my friend! After changing countries and entering a code-free vacation, i'll be reviewing your PR this week and evaluating how the important changes will influence streaming (which sounds pretty exciting and doable). Then i'll submit a PR for you and @p1nox to review.

**Comment by p1nox** [comment]
Thanks @flockonus, that would be awesome :feelsgood: :+1:

**Comment by gustavnikolaj** [comment]
@flockonus I thought that this was #24 actually - I was mistaken about the context. I only just noticed now, so I thought I'd mention it.

I would be glad if you would review #24 first. I know how to fix both this and #25. The unexpected-express testing tools are way more effective at testing these kinds of things than supertest. If you like what you see in #24 I'll be more than happy to contribute PR's for a fix for this problem as well as #25, and any other things you might struggle with.

I'll take a look at the PR tonight, to see if there's anything that needs an update - it's been laying around for a while :-) But it will be insignificant nitpicks if anything.

**Comment by gustavnikolaj** [comment]
Oh, I forgot that I landed the fix for this issue in #24. Sorry about that! It's been a while, so I forgot :-)

**Comment by gustavnikolaj** [comment]
Fixed when https://github.com/axiomzen/express-interceptor/commit/1a8716269733037a3645e9a5a743c1716ac0a946 was merged today

**Comment by p1nox** [comment]
Awesome, thanks @gustavnikolaj!

**Comment by gustavnikolaj** [comment]
:+1:
