### ISSUE TITLE
afterSend test: Replace fs.existsSync with the async counterpart

### ISSUE THREAD

**Issue by gustavnikolaj** [axiomzen/express-interceptor#26]
> It seems [existsSync will be deprecated](https://nodejs.org/api/fs.html#fs_fs_existssync_path), despite the async being uglier might make more sense?
-- @flockonus  https://github.com/axiomzen/express-interceptor/pull/24#discussion_r34631491

https://github.com/axiomzen/express-interceptor/blob/master/tests/afterSend.test.js

**Comment by gustavnikolaj** [comment]
> fs.exists() is an anachronism and exists only for historical reasons. There should almost never be a reason to use it in your own code.
>
> In particular, checking if a file exists before opening it is an anti-pattern that leaves you vulnerable to race conditions: another process may remove the file between the calls to fs.exists() and fs.open(). Just open the file and handle the error when it's not there.
>
>fs.exists() will be deprecated.
https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

Apparently the same is true for fs.exists.

**Comment by gustavnikolaj** [comment]
Replaced this issue with the PR #28

**Comment by p1nox** [comment]
Sidenote @gustavnikolaj : You shouldn't close an issue that is not fixed yet (not merged into master).

**Comment by gustavnikolaj** [comment]
Oh, sorry about that. I just thought that the PR would replace the issue, and that was where we would continue the discussion. :-)

**Comment by flockonus** [comment]
Agreed, also it's the beauty of the syntax `Fixes #26` it just auto closes :)
