### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gustavnikolaj** [axiomzen/express-interceptor#29]
@p1nox @flockonus

I need a new release out. I'm blocked on the work I'm doing at the moment, due to the bug #25 which was fixed since the last release.

**Comment by gustavnikolaj** [comment]
I'd appreciate if either of you would get in touch with me by email. gustavnikolaj@gmail.com

I haven't been able to find contact information for you online :-)

**Comment by p1nox** [comment]
A new release was published! Sorry for your inconvenients!. Also you can find contact info about us in [package.json](https://github.com/axiomzen/express-interceptor/blob/master/package.json#L26-L33).

**Comment by gustavnikolaj** [comment]
Thanks @p1nox. I don't know how I could miss your email addresses in the package.json :-) I guess I was too much in a hurry.
