### ISSUE TITLE
node js 4.x incompatibility 

### ISSUE THREAD

**Issue by nikolaybaldzhiev** [axiomzen/express-interceptor#35]
TypeError: buf.copy is not a function

var oldBody = Buffer.concat(chunks).toString('utf-8');

**Comment by algebris** [comment]
please update master with this issue patch!!!

**Comment by p1nox** [comment]
Fixed in https://github.com/axiomzen/express-interceptor/pull/37

**Comment by p1nox** [comment]
Fixed in https://github.com/axiomzen/express-interceptor/pull/37
