### ISSUE TITLE
should it only send string back?

### ISSUE THREAD

**Issue by bugushi** [axiomzen/express-interceptor#41]
hi, i wanna format my api response before send it back，for my income data will always be json, so i wanna just add a property into the json data, but seems intercept function can only handle string value, how can i avoid to JSON.parse first and JSON.stringify again, thank you very much 

here is my middleware code
```javascript
var interceptor = require('express-interceptor')

module.exports = interceptor((req, res) => {
  return {
    // Only HTML responses will be intercepted
    isInterceptable: () => {
      return true
    },

    // Appends a paragraph at the end of the response body
    intercept: (body, send) => {
      try {
        var result = JSON.parse(body)
        result.status = res.statusCode

        send(JSON.stringify(result))
      } catch (error) {
        // and how can i send the json parse error to next() function?
      }
    }
  }
})
```

**Comment by flockonus** [comment]
Hi @bugushi , I'm not sure you can do so without the current implementation. Please take a look at @fuminchao implementation, he might have some good advice for your needs - https://github.com/fuminchao/express-interceptor

**Comment by fuminchao** [comment]
@bugushi the ```body``` of method intercept will always be a string.
In my fork https://github.com/fuminchao/express-interceptor, the ```body``` will be a string if and only if the content-type of response is text compatible, such as "text/html", "text/plain", "application/json"
That means if your upstream response is binary, the ```body``` will be a buffer

**Comment by fuminchao** [comment]
@bugushi And I don't think you can transform errors into error status code and send back to clients. Because at the runtime of method ```intercept```, the headers are already sent back

**Comment by bugushi** [comment]
@flockonus thank you very much for recommendation

@fuminchao 如果我想对api返回做格式化，比如补充http状态，系统时间等；你觉得最佳实践是什么？谢谢

**Comment by bugushi** [comment]
i make it, thank you all very much, here is my code
```javascript
var Model = require('sequelize').Model

module.exports = (req, res, next) => {
  var resSendJson = res.json
  let result = {}

  res.json = (data) => {
    result.status = res.statusCode

    // 判断是否为 sequelize model 对象
    if (data instanceof Model && data.dataValues) {
      result.data = data.dataValues
    } else {
      result.data = data
    }

    resSendJson.call(res, result)
  }
  next()
}
```
