### ISSUE TITLE
Binary data

### ISSUE THREAD

**Issue by vinicius** [axiomzen/express-interceptor#44]
Hi!
I´m facing issues while intercepting/sending body with binary data, even when the interceptor does nothing with the content.
Example:

intercept: (body, send) => {
send(body);
}

I try this with some pdf files and they were all corrupted after the interception. Is there something that I may not paying attention regarding binary content?

Best regards,
Vinicius

**Comment by flockonus** [comment]
Yes, please see this fork https://github.com/fuminchao/express-interceptor
