### ISSUE TITLE
Spread the word ;)

### ISSUE THREAD

**Issue by p1nox** [axiomzen/express-interceptor#6]
Check [express-hijackresponse](https://www.npmjs.com/package/express-hijackresponse) "Dependents" packages, and make a PR into those projects removing express-hijackresponse while using express-interceptor:

* express-jsxtransform is a good start because of the hype of React.

**Comment by pnavarrc** [comment]
What needs to be done?

**Comment by p1nox** [comment]
Description updated.

**Comment by fer8a** [comment]
express-jsxtransform PR sent.

**Comment by gustavnikolaj** [comment]
@fer8a thanks, it's merged now ;-)

I'll just add a few more that I know of here:

- [gustavnikolaj/express-autoprefixer](https://github.com/gustavnikolaj/express-autoprefixer)
- [papandreou/express-compiless](https://github.com/papandreou/express-compiless)

There's a few more, but those use streaming as far as I remember.

**Comment by gustavnikolaj** [comment]
I'll be happy to do some of the work, but I cannot promise when I'll get around to it :-)

**Comment by fer8a** [comment]
Hi again guys, express-compiless PR sent.

**Comment by pnavarrc** [comment]
Consider sending an email to http://nodeweekly.com/

**Comment by p1nox** [comment]
I think we can do it after [this](https://github.com/papandreou/express-compiless/pull/10) gets merged, and adding to the readme file a section "Who is using it" we can send the email. Also we can add streaming as part of our roadmap. cc @flockonus

**Comment by p1nox** [comment]
BTW, [this](https://github.com/papandreou/express-compiless/pull/10#issuecomment-91344710) comment is awesome! :feelsgood:

**Comment by gustavnikolaj** [comment]
@p1nox I'll review and probably merge that PR tomorrow at work.

**Comment by Munter** [comment]
https://github.com/One-com/livestyle is also using express-hijackresponse in https://github.com/One-com/livestyle/blob/master/lib/middleware/injectLiveStyleScriptIncludeIntoHtml.js

**Comment by Munter** [comment]
[connect-inject](https://github.com/danielhq/connect-inject/blob/master/index.js) would also be a good candidate for a PR, since it is also messing with the response object

**Comment by fer8a** [comment]
Greetings everyone, express-autoprefixer PR sent.

**Comment by p1nox** [comment]
Merged on express-compiless: https://github.com/papandreou/express-compiless/pull/10#issuecomment-98609635

**Comment by p1nox** [comment]
Next packages waiting for PR ;):

* https://github.com/papandreou/express-processimage
* https://github.com/One-com/livestyle

Thanks to @gustavnikolaj @fer8a @Munter for all the help :+1:.

**Comment by Munter** [comment]
I'm also using interceptor in this project: https://github.com/Munter/express-systemjs-translate

Still in prototyping stage and waiting for some syncing with systemjs, so not ready to be linked to yet

**Comment by p1nox** [comment]
Awesome @Munter! Let us know :+1:

**Comment by p1nox** [comment]
No need to open more PRs :wink:, closing for now.
